### ISSUE TITLE
issues with "params"

### ISSUE THREAD

**Issue by erwanj** [damavis/airflow-pentaho-plugin#15]
we have just upgraded from airflow v1.10.11 to airflow v2.2.4.
We are getting the following error in airflow. This dag was working correctly before the migration.
```
Broken DAG: [/opt/airflow/dags/dag1.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/serialization/serialized_objects.py", line 578, in serialize_operator
    serialize_op['params'] = cls._serialize_params_dict(op.params)
  File "/usr/local/lib/python3.8/dist-packages/airflow/serialization/serialized_objects.py", line 451, in _serialize_params_dict
    if f'{v.__module__}.{v.__class__.__name__}' == 'airflow.models.param.Param':
AttributeError: 'str' object has no attribute '__module__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/serialization/serialized_objects.py", line 939, in to_dict
    json_dict = {"__version": cls.SERIALIZER_VERSION, "dag": cls.serialize_dag(var)}
  File "/usr/local/lib/python3.8/dist-packages/airflow/serialization/serialized_objects.py", line 851, in serialize_dag
    raise SerializationError(f'Failed to serialize DAG {dag.dag_id!r}: {e}')
airflow.exceptions.SerializationError: Failed to serialize DAG 'dag1': 'str' object has no attribute '__module__'
```

The dag looks like : 
```
# DAG creation
with DAG (
    dag_id="dag1",
    default_args=DEFAULT_ARGS,
    max_active_runs=1,
    description='dag1',
    schedule_interval=WORKFLOW_SCHEDULE_INTERVAL,
    catchup=False
) as dag :

    extract_tables = KitchenOperator (
        pdi_conn_id='pdi_default',
        task_id="extract_tables",
        directory=PROJECT_DIRECTORY,
        job="jb_01_load_ods_tables",
        file=PROJECT_DIRECTORY+"jb_01_load_ods_tables.kjb",
        params={
            "date": '{{ ds }}'
        }
    )
```
If we remove ` "date": '{{ ds }}'`, the error in airflow disapears.

Is it possible that the issue is linked with airflow-pentaho-plugin?

**Comment by piffall** [comment]
Hello @erwanj 

I don't think so. It seems that this is an Airflow issue on DAG serialization. I found a similar issue on Airflow repository:
[https://github.com/apache/airflow/issues/20875](https://github.com/apache/airflow/issues/20875)

I will investigate more on this.

Please, take a look to [DAG serialization](https://airflow.apache.org/docs/apache-airflow/stable/dag-serialization.html), 
disabling it, may be a temporal solution for you.

**Comment by piffall** [comment]
Please, try to run:
```bash
airflow dags reserialize
```

**Comment by erwanj** [comment]
it seems that it works now.
I had to : 
`from airflow.models.param import Param`
and use the following syntax for params : 
```
        params={
           'date': Param('{{ ds }}')
        }
```

Thank you for your help

**Comment by piffall** [comment]
It seems that `params` should not be used, because it's already beeing used by BaseOperator.
I found a [conversation](https://www.mail-archive.com/users@airflow.apache.org/msg00713.html) about this.

This argument, `params`, will be renamed to `task_params`.

**Comment by erwanj** [comment]
Thank you very much for your help.
